name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  SNAPPY_SHOTS_DB_NAME: "snappy_shots"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Setup database
        run: |
          sbt Test/flywayClean
          sbt Test/flywayMigrate
      - name: Run tests
        run: sbt clean coverage test
      - name: Coverage Report
        run: sbt coverageReport
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck Test/scalafmtCheck
